algoritmo "Calculadora Simples"

var

   n1, n2, sm, sb, m, d: real

inicio

escreval ("Digite o primeiro número: ")
leia (n1)

escreval ("Digite o segundo número: ")
leia (n2)

sm <- n1 + n2
sb <- n1 - n2
m <- n1 * n2
d <- n1 / n2

escreval ("A soma dos números é: ", sm)
escreval ("A subtração dos números é: ", sb)
escreval ("A multiplicação dos números é: ", m)
escreval ("A divisão dos números é: ", d)

fimalgoritmo