algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

F, C: real

inicio

Escreval ("Qual a temperatura aqui? ")
Leia(F)
C<- (F-32)/1.8
escreva ("A temperatura no Brasil estaria, ", C:4:1)

fimalgoritmo