Algoritmo "Atividade 62 - Ler Matriz"

Var

   M : vetor[1..3, 1..2] de Inteiro  /
   l, c : Inteiro

Inicio

   Para l <- 1 ate 3 faca
        Para c <-  1 ate 2 faca
             Escreva("Digite o valor da posicaoo [",l,",",c," ] : ")
             Leia( M[l,c] )
        FimPara
   FimPara
    Para l <- 1 ate 3 faca
        Para c <-  1 ate 2 faca
             Escreva(M[l,c])
        FimPara
        escreval()
   FimPara

Fimalgoritmo