//Estruturas de Repetição 3 - Curso de Algoritmos #11 - Gustavo Guanabara - Contar 1  a 10
//Anne Carvalho

Algoritmo " Contador1a10"

Var
  C: Inteiro
Inicio

   Para C <- 1 ate 10 passo 2 faca
      Escreval(C)
   FimPara

Fimalgoritmo

//---------------------------------------------------------------

Algoritmo " Contador1a10"

Var
  C: Inteiro
Inicio

   Para C <- 1 ate 10 passo -1 faca
      Escreval(C)
   FimPara

Fimalgoritmo

