//Exercícios de Algoritmo Resolvidos - Curso de Algoritmos #06 - Gustavo Guanabara - Creuza Idade
//Anne Carvalho

Algoritmo "Creuza Idade"

Var

AnoAtual, AnoNascimento, idade: Real

Inicio
      EscrevaL("Em qual ano estamos?")
      Leia(AnoAtual)

      EscrevaL("Em qual ano nasci?")
      Leia(AnoNascimento)

      idade <- AnoAtual - AnoNascimento

      EscrevaL("Minha idade é ", idade)

Fimalgoritmo
