Algoritmo "4.operadores-logicos-e-relacionais"

// Autor(a)    : Yuri Carvalho Teixeira
// Data atual  : 25/05/2023
Var
   a, b, c: inteiro


Inicio
   a<- 2
   b<- 3
   c<- 5
   Escreval(a>b)
   Escreval(a=b)
   Escreval(a<>b)
   Escreval(a>2)
   Escreval(a>=2)
   Escreval(c=(a+b))
   Escreval(c=(b^a))
   Escreval(c<=(b^a))
   Escreval(b<=(c%2))
   Escreval(1=(c%2))
   Escreval(verdadeiro e falso)
   Escreval((a=b) ou (c>a))
   Escreval(nao((a=b) ou (c>a)))
Fimalgoritmo