algoritmo "Creuza02"

// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Gustavo Guanabara]
// Conteúdo    : [Exercícios de algoritimos aula 6 ]
// Descrição   : [Entender os operadores lógicos]
// Autor(a)    : [Aesley Soares]
// Data atual  : [29/05/2023]
var

reais, dolares : real

inicio

escreval("Quantos reais eu tenho?")
leia(reais)
escreval("R$:", reais)
dolares <- reais/4.99 //cotação dia 29/05/2023
escreval("Quantos dólares eu tenho? U$:", dolares)

fimalgoritmo