algoritmo "Nome do Programa"
// --------------------------------------------------
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Gustavo Guanabara]
// Conteúdo    : [Estrutura de repetição 3 aula 11 ]
// Descrição   : [Entender estruturas de repetição 3]
// Autor(a)    : [Aesley Soares]
// Data atual  : [05/06/2023]
// --------------------------------------------------
var

C: inteiro

inicio
C <- 10
para C de 10 ate 1 faca
    
    escreval (C)
fimpara

fimalgoritmo