algoritmo "Creuza03"

// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Gustavo Guanabara]
// Conteúdo    : [Exercícios de algoritimos aula 6 ]
// Descrição   : [Entender os operadores lógicos]
// Autor(a)    : [Aesley Soares]
// Data atual  : [29/05/2023]
var

celsius, fahrenheit : real

inicio

escreval("qual a temperatura aqui?")
leia(fahrenheit)
celsius <- (fahrenheit - 32) * 5 / 9
escreval("No brasil estaria em: ", celsius:4:1)


fimalgoritmo