algoritmo "Creuza04"

// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Gustavo Guanabara]
// Conteúdo    : [Exercícios de algoritimos aula 6 ]
// Descrição   : [Entender os operadores lógicos]
// Autor(a)    : [Aesley Soares]
// Data atual  : [29/05/2023]
var

preco, imposto : real

inicio

escreval ("Qual o preço do produto? Us$")
leia(preco)
escreval("Us$: ", preco)
imposto <- preco * 0.6
escreval("O imposto será de Us$", imposto:5:2)
fimalgoritmo